// Bundles packs/<slug>/** into src/generated/packs.ts so the Worker can serve
// them without a filesystem. Run `npm run build:packs` after editing any pack.
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, relative, posix } from 'node:path';

const PACKS_DIR = 'packs';
const OUT = 'src/generated/packs.ts';

// Human metadata per slug — keep in sync with the /packs pages.
const META = {
  'cicd-automation': {
    name: 'Fabric CI/CD Automation Pack',
    zipName: 'fabric-cicd-automation-pack.zip',
  },
  'pyspark-templates': {
    name: 'Fabric PySpark & Notebook Templates',
    zipName: 'fabric-pyspark-templates.zip',
  },
  'governance-framework': {
    name: 'Fabric Governance & Security Framework',
    zipName: 'fabric-governance-framework.zip',
  },
  'migration-toolkits': {
    name: 'Fabric Migration Toolkits',
    zipName: 'fabric-migration-toolkits.zip',
  },
  'workspace-monitoring': {
    name: 'Fabric Workspace Monitoring Framework',
    zipName: 'fabric-workspace-monitoring.zip',
  },
};

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else if (entry.isFile()) out.push(full);
  }
  return out;
}

const slugs = (await readdir(PACKS_DIR, { withFileTypes: true }))
  .filter((e) => e.isDirectory())
  .map((e) => e.name);

const packs = {};
for (const slug of slugs) {
  const files = {};
  for (const file of await walk(join(PACKS_DIR, slug))) {
    const rel = posix.normalize(relative(join(PACKS_DIR, slug), file).split(/[\\/]/).join('/'));
    files[rel] = await readFile(file, 'utf8');
  }
  const meta = META[slug] ?? { name: slug, zipName: `${slug}.zip` };
  packs[slug] = { ...meta, files };
}

const banner = `// GENERATED by scripts/build-packs.mjs — do not edit by hand.\n// Run \`npm run build:packs\` after changing anything under packs/.\n`;
const body = `export interface Pack {\n  name: string;\n  zipName: string;\n  files: Record<string, string>;\n}\n\nexport const PACKS: Record<string, Pack> = ${JSON.stringify(packs, null, 2)};\n\nexport function packFileList(slug: string): string[] {\n  return Object.keys(PACKS[slug]?.files ?? {}).sort();\n}\n`;

await writeFile(OUT, banner + '\n' + body, 'utf8');
const total = Object.values(packs).reduce((n, p) => n + Object.keys(p.files).length, 0);
console.log(`build-packs: ${slugs.length} pack(s), ${total} file(s) -> ${OUT}`);
